### PR TITLE
fix console IP display, host name prefix, have2 MACs / house

### LINKED ISSUE #49: Sometimes the wrong IP address shows up in the terminal output
In the module aaNetwork.cpp in the routine cfgToConsole() the display of the robot IP address is sometime incorrect. Specific use case was the address being assigned to Doug's robot on Andrew's network, 192.168.2.158 was displayed as 0.104.64.63. We put in a debug line that help ed uncover this issue an the code that actually worked was WiFi.localIP().toString(); This can be displayed with far less work and is correct. The code _convert.ipToString(WiFi.localIP().cStr());

### PR DESCRIPTION
**Pull request by nerdoug**
fix console IP display, host name prefix, recognize 2 MAC's per house
Fixes #49

### CODE REVIEW

**Comment by nerdoug** [comment]
I'll do a quick test to see if I can replicate the problem, and review the changes in commit 918d769

**Comment by nerdoug** [comment]
I get same crash, repeating when I load my main branch. Since I can replicate it, I should be able to narrow it down.

**Comment by nerdoug** [comment]
made this change in main.h:
//const char* HOST_NAME_PREFIX = "HexaFloorRide"; // Prefix for our unique network name.
const char* HOST_NAME_PREFIX = "Hexbot"; // Prefix for our unique network name.

and my start up now works fine. This was the first thing I tried so there are no other variables. Going to change it back and confirm problem reappears.

**Comment by nerdoug** [comment]
yup, changing to
const char* HOST_NAME_PREFIX = "HexaFloorRide"; // Prefix for our unique network name.
//const char* HOST_NAME_PREFIX = "Hexbot"; // Prefix for our unique network name.

caused the crash to return. I probably added the prefix change to issue as an after thought without testing it - my bad.
Wonder if it's a problem with the length of the name. prefix + mac address went from 6+12 = 18 bytes to 13 + 12 = 25 bytes?

**Comment by nerdoug** [comment]
I'm doing a git merge to revert to the Hexbot prefix for now, under a branch named debug.

**Comment by theAgingApprentice** [comment]
Yes I had this issue when I changed the prefix in the past. If you change the length the issue will go away. The size must accommodate the full MQTT path name. I forget how long I set it to but it clearly needs more.

**Pull request merged**
